project_id = "uqgxxgbhvqjxrpotyilj"

[functions.update-transaction-payment]
verify_jwt = true

[functions.reassign-rider-branch]
verify_jwt = true

[functions.create-purchase]
verify_jwt = true

[functions.fix-zero-transactions]
verify_jwt = true

[functions.get-nearby-riders]
verify_jwt = false

[functions.send-order-request]
verify_jwt = false

[functions.rider-respond-order]
verify_jwt = false

[functions.update-rider-location-live]
verify_jwt = false

[functions.create-xendit-invoice]
verify_jwt = false

[functions.xendit-webhook]
verify_jwt = false
